version: '2'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=lms
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - log_db:/var/lib/postgresql/data/
      
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "9093:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lms
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  

  swagger-ui:
   image: swaggerapi/swagger-ui
   container_name: swagger_ui_container
   ports:
      - "8081:8080"
   volumes:
      - ./doc:/usr/share/nginx/html/doc
   environment:
      API_URL: ""
      
volumes:
  log_db:
    
    
      
  
          
